po_platforme_homepage:
    path:     /hello/{name}
    defaults: { _controller: POPlatformeBundle:Default:index }

# src/OC/PlatformBundle/Resources/config/routing.yml

hello_the_world:
    path:     /hello-world
    defaults: { _controller: POPlatformeBundle:Advert:index }