<?php

namespace Pouce\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
	public function findLikeName($cityName)
	{
		$qb = $this	-> createQueryBuilder('c')
					-> where('c.name LIKE :cityName')
					-> setParameter('cityName', '%'.$cityName.'%')
			;

		return $qb->getQuery()->getResult() ;
	}

}
