<?php

namespace Pouce\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * EditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditionRepository extends EntityRepository
{
	public function findNextEditionBySchool($user)
	{
        $now = new \DateTime();
		$qb = $this	-> createQueryBuilder('e')
                    -> andWhere('e.dateOfEvent > :today')
                     ->setParameter('today', $now->format("Y-m-d"))
                    -> join('e.schools','s')
                    -> andWhere('s.name = :schoolName')
                     ->setParameter('schoolName', $user->getSchool()->getName())
                    -> orderBy('e.dateOfEvent','ASC')
                    ->setMaxResults(1);
                    
        // DO NOT put "->getSingleResult()" here (because NoResultExeption cached somewhere else)
		return $qb->getQuery();
	}

	public function findPreviousEditionBySchool($user)
	{
        $now = new \DateTime();
		$qb = $this	-> createQueryBuilder('e')
                    -> andWhere('e.dateOfEvent <= :today')
                     ->setParameter('today', $now->format("Y-m-d"))
                    -> join('e.schools','s')
                    -> andWhere('s.name = :schoolName')
                     ->setParameter('schoolName', $user->getSchool()->getName())
                    -> orderBy('e.dateOfEvent','DESC')
                    ->setMaxResults(1);

        // DO NOT put "->getSingleResult()" here (because NoResultExeption cached somewhere else)
		return $qb->getQuery()->getSingleResult();
	}
}
