<?php

namespace Pouce\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
	// To get all informations for the ranking
	public function getAllResultsInEdition($idEdition)
	{
		$qb = $this	-> createQueryBuilder('r')
                    -> join('r.team','t')
                    -> addSelect('t')
                    -> join('t.edition', 'e')
                    -> where('e.id = :idEdition')
                     ->setParameter('idEdition', $idEdition)
                    -> join('t.users','u') //Il faut assurer la jointure (voir s'il y a pas moyen de faire autrement qu'une relation bidirectionnel)
                    -> addSelect('u')
                    -> join('u.school','s')
                    -> addSelect('s')
                    -> join('r.position','p')
                    -> addSelect('p')
                    -> leftjoin('r.comment','c')
                    -> addSelect('c')
                    -> addOrderBy('r.isValid', 'DESC')
                    -> orderBy('(p.distance / 1000) - (r.lateness * 100)','DESC');

		return $qb->getQuery()->getResult();
	}	

	public function getAllResultsByYear($year)
	{
		$qb = $this	-> createQueryBuilder('r')
                    -> join('r.team','t')
                    -> addSelect('t')
                    -> join('t.edition', 'e')
                    -> addSelect('e')
					-> where('YEAR(e.dateOfEvent) = :year')
                     ->setParameter('year', $year)
                    -> join('t.users','u') //Il faut assurer la jointure (voir s'il y a pas moyen de faire autrement qu'une relation bidirectionnel)
                    -> addSelect('u')
                    -> join('u.school','s')
                    -> addSelect('s')
                    -> join('r.position','p')
                    -> addSelect('p')
                    -> leftjoin('r.comment','c')
                    -> addSelect('c')
                    -> addOrderBy('r.isValid', 'DESC')
                    -> addOrderBy('(p.distance / 1000) - (r.lateness * 100)','DESC');

		return $qb->getQuery()->getResult();
	}

	// Récupère le résult d'une team
	public function getResultTeam($team)
	{
		$qb = $this	-> createQueryBuilder('r')
					-> where('r.team = :idTeam')
					 ->setParameter('idTeam', $team->getId());

		return $qb->getQuery();
	}
}
