# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CHEFPOUCEUX:   ROLE_USER
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_CHEFPOUCEUX]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # On crée un pare-feu uniquement pour le formulaire
        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern: ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            anonymous:      true
            remember_me:
                key:        %secret% # %secret% est un paramètre de paramètre.yml

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/team, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/allmyusers, role: ROLE_CHEFPOUCEUX }