# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CHEFPOUCEUX:   ROLE_USER
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_CHEFPOUCEUX]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # On crée un pare-feu uniquement pour le formulaire
        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern: ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path : true
                default_target_path: /user/mainpage
            logout:
                path:       fos_user_security_logout
                target:     /
            anonymous:      true
            remember_me:
                key:        %secret% # %secret% est un paramètre de paramètre.yml
        
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
        api_doc:
            pattern:      ^/api/doc
            security:     false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_CHEFPOUCEUX }
        - { path: ^/team/result/show, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/team, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/allmyusers, role: ROLE_CHEFPOUCEUX }
        - { path: ^/superAdmin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/map/, role: ROLE_CHEFPOUCEUX }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        # - { path: ^/ranking/, role: ROLE_CHEFPOUCEUX }
