# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    wsse.security.authentication.provider:
        class: Pouce\UserBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - '' # User Provider
            - '%kernel.cache_dir%/security/nonces'
        public: false

    # wsse.security.authentication.listener:
    #     class: Pouce\UserBundle\Security\Firewall\WsseListener
    #     arguments: ['@security.token_storage', '@security.authentication.manager']
    #     public: false
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
