pouce_team_add:
    path:     /add
    defaults: { _controller: PouceTeamBundle:Team:addTeam }

pouce_result_add:
    path:   /result/add/{editionId}
    defaults: { _controller: PouceTeamBundle:Result:addResult }

pouce_result_edit:
    path:   /result/edit/{editionId}
    defaults: { _controller: PouceTeamBundle:Result:editResult }

pouce_comment_create:
    path:   /comment/create/{editionId}
    defaults: { _controller: PouceTeamBundle:Comment:createComment }

pouce_comment_edit:
    path:   /comment/edit/{editionId}
    defaults: { _controller: PouceTeamBundle:Comment:editComment }

pouce_comment_photo_upload:
    path:   /comment/uploadPhoto/{editionId}
    defaults: { _controller: PouceTeamBundle:Comment:uploadPhoto }
    requirements:
        _method: POST

pouce_result_show:
    path:   /result/show/{id}
    defaults: { _controller: PouceTeamBundle:Result:showResult }

pouce_team_edit:
    path:   /edit/{id}
    defaults: { _controller: PouceTeamBundle:Team:editTeam }

pouce_team_position_show:
    path: /position/all/{editionId}
    defaults: { _controller: PouceTeamBundle:Position:showPositions}

pouce_team_position_edit:
    path: /position/edit/{positionId}
    defaults: { _controller: PouceTeamBundle:Position:editPosition}

pouce_team_position_delete:
    path: /position/delete/{positionId}
    defaults: { _controller: PouceTeamBundle:Position:deletePosition}

pouce_position_add:
    path:   /position/add/{editionId}
    defaults: { _controller: PouceTeamBundle:Position:addPosition, editionId: 0  }

pouce_position_add_with_hour:
    path:   /position/add_post_edition/{editionId}
    defaults: { _controller: PouceTeamBundle:Position:addPositionWithHour, editionId: 0  }

pouce_team_delete:
    path: /delete/{id}
    defaults: { _controller: PouceTeamBundle:Team:deleteTeam }
