pouce_team_homepage:
    path:     /
    defaults: { _controller: PouceTeamBundle:Default:index }

pouce_team_add:
    path:     /add
    defaults: { _controller: PouceTeamBundle:Team:addTeam }

pouce_result_add:
    path:   /result/add
    defaults: { _controller: PouceTeamBundle:Result:addResult }

pouce_comment_create:
    path:   /comment/create
    defaults: { _controller: PouceTeamBundle:Result:createComment }

pouce_result_show:
    path:   /result/{id}
    defaults: { _controller: PouceTeamBundle:Result:showResult }

pouce_team_edit:
    path:   /edit/{id}
    defaults: { _controller: PouceTeamBundle:Team:editTeam }