pouce_team_add:
    path:     /add
    defaults: { _controller: PouceTeamBundle:Team:addTeam }

pouce_result_add:
    path:   /result/add/{editionId}
    defaults: { _controller: PouceTeamBundle:Result:addResult }

pouce_result_edit:
    path:   /result/edit/{editionId}
    defaults: { _controller: PouceTeamBundle:Result:editResult }

pouce_comment_create:
    path:   /comment/create
    defaults: { _controller: PouceTeamBundle:Result:createComment }

pouce_comment_photo_upload:
    path:   /comment/uploadPhoto
    defaults: { _controller: PouceTeamBundle:Result:uploadPhoto }
    requirements:
        _method: POST

pouce_result_show:
    path:   /result/{id}
    defaults: { _controller: PouceTeamBundle:Result:showResult }

pouce_team_edit:
    path:   /edit/{id}
    defaults: { _controller: PouceTeamBundle:Team:editTeam }

pouce_position_add:
    path:   /position/add/{editionId}
    defaults: { _controller: PouceTeamBundle:Result:addPosition, editionId: 0  }


pouce_team_delete:
    path: /delete/{id}
    defaults: { _controller: PouceTeamBundle:Team:deleteTeam }