services:
    pouce_team.trajet:
        class: Pouce\TeamBundle\Trajet\PouceTrajet
#    pouce_team.example:
#        class: Pouce\TeamBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
