pouce_site_listeEdition:
    path:   /
    defaults: {_controller: PouceSuperAdminBundle:SuperAdmin:superAdmin }

pouce_site_config:
    path:   /config/
    defaults: { _controller: PouceSuperAdminBundle:SuperAdmin:config }

pouce_superAdmin_recalcul:
    path: /recalcul/{editionId}
    defaults: { _controller: PouceTeamBundle:Result:recalcul }

pouce_superAdmin_lancement:
    path: /launch/{editionId}
    defaults: { _controller: PouceSuperAdminBundle:SuperAdmin:addPositionInitial }

pouce_superAdmin_checkAllParcipants:
    path:   /{editionId}
    defaults: { _controller: PouceSuperAdminBundle:SuperAdmin:superOrganisationPage }
    requirements:
        editionId:  \d+

pouce_superAdmin_checkParcipantsEdition:
    path:   /{editionId}/{schoolId}
    defaults: { _controller: PouceSuperAdminBundle:SuperAdmin:checkParcipantsEdition }
    requirements:
        editionId:  \d+
        schoolId:  \d+

pouce_superAdmin_admin_comment_edit:
    path:   /comment/edit/{teamId}
    defaults: { _controller: PouceTeamBundle:Comment:editCommentAdmin }

pouce_superAdmin_comment_photo_upload:
    path:   /comment/uploadPhoto/{teamId}
    defaults: { _controller: PouceTeamBundle:Comment:uploadPhotoAdmin }

pouce_superAdmin_add_edition:
    path:   /addEdition/
    defaults: { _controller: PouceSiteBundle:Edition:addEdition }

pouce_superAdmin_edit_edition:
    path:   /editEdition/{id}
    defaults: { _controller: PouceSiteBundle:Edition:editEdition }

pouce_superAdmin_add_school:
    path:   /addSchool/
    defaults: { _controller: PouceUserBundle:School:addSchool }

pouce_superAdmin_edit_school:
    path:   /editSchool/{id}
    defaults: { _controller: PouceUserBundle:School:editSchool }

pouce_superAdmin_school_in_edition:
    path:   /schoolsInEdition/{id}
    defaults: { _controller: PouceUserBundle:School:schoolsInEdition }

pouce_superAdmin_add_school_in_edition:
    path:   /addSchoolsInEdition/{schoolId}/{editionId}
    defaults: { _controller: PouceUserBundle:School:addSchoolsInEdition }

pouce_superAdmin_delete_school_in_edition:
    path:   /deleteSchoolsInEdition/{schoolId}/{editionId}
    defaults: { _controller: PouceUserBundle:School:deleteSchoolsInEdition }

pouce_superAdmin_foward_step_edition:
    path:   /fowardStepEdition/{editionId}
    defaults: { _controller: PouceSiteBundle:Edition:fowardStepEdition }

pouce_superAdmin_backward_step_edition:
    path:   /backwardStepEdition/{editionId}
    defaults: { _controller: PouceSiteBundle:Edition:backwardStepEdition }
