<?php

namespace Pouce\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{
	// To get all schools that participate to the competition on the year
	public function getAllSchoolParticipate($year)
	{
		$qb = $this	-> createQueryBuilder('s')
                    -> join('s.editions','e')
                    -> addSelect('e')
                    -> where('YEAR(e.dateOfEvent) = :year')
                     ->setParameter('year', $year)
                    -> orderBy('s.name','ASC')
                    ;


		return $qb ;					
	}

	// To get all schools that participate to the competition in a specific edition
	public function findAllSchoolParticipateByEdition($editionId)
	{
		$qb = $this	-> createQueryBuilder('s')
                    -> join('s.editions','e', 'WITH', 'e.id = :editionId')
                     ->setParameter('editionId', $editionId)
                    -> addSelect('e')
                    -> orderBy('s.name','ASC')
                    ;


		return $qb->getQuery()->getResult() ;					
	}
}
