pouce_site_homepage:
    path:     /
    defaults: { _controller: PouceSiteBundle:Site:index }

pouce_site_regles:
    path:     /regles
    defaults: { _controller: PouceSiteBundle:Site:regles }

pouce_site_archives:
    path:     /archives
    defaults: { _controller: PouceSiteBundle:Site:archives }

pouce_site_asso:
    path:     /association
    defaults: { _controller: PouceSiteBundle:Site:asso }

pouce_site_conseils:
    path:     /conseils
    defaults: { _controller: PouceSiteBundle:Site:conseils }

pouce_site_edition:
    path:     /edition
    defaults: { _controller: PouceSiteBundle:Site:edition }

pouce_site_editions_precedente:
    path:     /editions_precedentes
    defaults: { _controller: PouceSiteBundle:Site:editionPrecedente }

pouce_site_liens:
    path:     /liens
    defaults: { _controller: PouceSiteBundle:Site:liens }

pouce_site_organisateurs:
    path:     /organisateurs
    defaults: { _controller: PouceSiteBundle:Site:organisateurs }

pouce_site_videos:
    path:     /videos
    defaults: { _controller: PouceSiteBundle:Site:videos }

pouce_site_records:
    path:     /records
    defaults: { _controller: PouceSiteBundle:Site:records }

pouce_site_ranking:
    path:     /ranking/{idEdition}
    defaults: { _controller: PouceSiteBundle:Ranking:ranking, idEdition: 1 }
    # requirements: