pouce_user_addinformations:
    path:     /addInformations
    defaults: { _controller: PouceUserBundle:User:addInformations }

pouce_user_mainpage:
    path:     /mainpage
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PouceUserBundle:User:mainpage.html.twig'

pouce_user_checkParticipants:
    path:     /allmyusers
    defaults: { _controller: PouceUserBundle:User:organisationPage }

pouce_user_uploadImageProfil:
    path:     /uploadImageProfil
    defaults: { _controller: PouceUserBundle:User:uploadImageProfil}
    requirements:
        _method:  POST

pouce_user_editUserPage:
    path:     /editUserPage
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PouceUserBundle:User:editUserPage.html.twig'