pouce_user_addinformations:
    path:     /addInformations
    defaults: { _controller: PouceUserBundle:User:addInformations }

pouce_user_mainpage:
    path:     /mainpage
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PouceUserBundle:User:mainpage.html.twig'

pouce_user_uploadImageProfil:
    path:     /uploadImageProfil
    defaults: { _controller: PouceUserBundle:User:uploadImageProfil}
    requirements:
        _method:  POST

pouce_user_edit:
    path:     /edit/{id}
    defaults: { _controller: PouceUserBundle:User:editUser }
