services:
    pouce_user.registration.form.type:
        class: Pouce\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: pouce_user_registration }
    pouce_user_registration_listener:
        class: Pouce\UserBundle\EventListener\UserRegistrationListener
        tags:
            - { name: kernel.event_subscriber }
    pouce_user.user:
        class: Pouce\UserBundle\Services\PouceUser
    wsse.security.authentication.listener:
        class:  Pouce\UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager","@logger"]
        tags:
            - { name: monolog.logger, channel: wsse }
#    pouce_user.example:
#        class: Pouce\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
